
import javafx.beans.binding.Bindings;
import javax.swing.JButton;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MIGUEL_CUPUL
 */
public class Ventana2 extends javax.swing.JDialog {
    DefaultTableModel modelo;
    /**
     * Creates new form Venatan2
     */
    public Ventana2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(710, 410);
        setTitle("MÉTODOS NUMÉRICOS_ERRORES");
        setLocationRelativeTo(null);
        setResizable(false);
        modelo = new DefaultTableModel();
        modelo.addColumn("ERROR ABSOLUTO");
        modelo.addColumn("ERROR RELATIVO");
        modelo.addColumn("ERROR PORCENTAJE");
        tabla.setModel(modelo);
        
      
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jValor1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jValor2 = new javax.swing.JTextField();
        opc2 = new javax.swing.JRadioButton();
        opc1 = new javax.swing.JRadioButton();
        jvalor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(741, 704, 199, 0);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESA EL VALOR REAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 70, 131, 30);

        jValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor1ActionPerformed(evt);
            }
        });
        getContentPane().add(jValor1);
        jValor1.setBounds(150, 100, 133, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESA EL VALOR APROXIMADO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 70, 190, 30);

        jValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValor2ActionPerformed(evt);
            }
        });
        getContentPane().add(jValor2);
        jValor2.setBounds(340, 100, 178, 30);

        buttonGroup1.add(opc2);
        opc2.setForeground(new java.awt.Color(255, 255, 255));
        opc2.setText("REDONDEO");
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });
        getContentPane().add(opc2);
        opc2.setBounds(150, 180, 130, 23);

        buttonGroup1.add(opc1);
        opc1.setForeground(new java.awt.Color(255, 255, 255));
        opc1.setSelected(true);
        opc1.setText("TRUNCAMIENTO");
        opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc1ActionPerformed(evt);
            }
        });
        getContentPane().add(opc1);
        opc1.setBounds(150, 150, 130, 23);
        getContentPane().add(jvalor);
        jvalor.setBounds(340, 160, 156, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NÚMERO DE DÍGITOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 140, 131, 20);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 250, 452, 94);

        jIngresar.setText("INGRESAR");
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jIngresar);
        jIngresar.setBounds(480, 210, 100, 23);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TECNOLÓGICO SUPERIOR DE VALLADOLID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 30, 347, 21);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(464, 672, 0, 0);

        Borrar.setText("ELIMNAR FILA");
        Borrar.setName(""); // NOI18N
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(Borrar);
        Borrar.setBounds(441, 350, 140, 23);
        Borrar.getAccessibleContext().setAccessibleDescription(""); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c5e2dc63db1c67c0ec5f695dbbcd9096.png"))); // NOI18N
        jLabel6.setRequestFocusEnabled(false);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, -60, 710, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor2ActionPerformed
        // TODO add your handling code here:
        jValor2.setText("");
    }//GEN-LAST:event_jValor2ActionPerformed

    private void jValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValor1ActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc2ActionPerformed

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
        double a,b, total;
        int c;
        
        a = Double.parseDouble(jValor1.getText());
        b = Double.parseDouble(jValor2.getText());
        c = Integer.parseInt(jvalor.getText());
        
        Operaciones op = new Operaciones();
        double a1 = op.absoluto(a, b);
        double b2 = op.relativo(a, b);
        double c3 = op.porcentaje(a, b);
        if (opc2.isSelected()) {

            double abso = (op.redondearDecimales(a1, c));
            double rela = (op.redondearDecimales(b2, c));
            double porc = (op.redondearDecimales(c3, c));
            Object info[]={abso,rela,porc};
            modelo.addRow(info);

        } else {
            double abso = (op.truncamiento(a1, c));
            double rela = (op.truncamiento(b2, c));
            double porc = (op.truncamiento(c3, c));
            Object info[]={abso,rela,porc};
            modelo.addRow(info);
    }//GEN-LAST:event_jIngresarActionPerformed

    }
    private void opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc1ActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        int fila = tabla.getSelectedRow();
        if(fila>=0){
            modelo.removeRow(fila);
        }
    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana2 dialog = new Ventana2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jValor1;
    private javax.swing.JTextField jValor2;
    private javax.swing.JTextField jvalor;
    private javax.swing.JRadioButton opc1;
    private javax.swing.JRadioButton opc2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
